[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "delineator"
version = "2.0.0"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "geopandas>=0.13",
    "shapely>=2.0",
    "pandas>=2.0",
    "numpy>=1.24",
    "matplotlib>=3.7",
    "pysheds>=0.5",
    "pyproj>=3.6",
    "click>=8.0",
    "pooch>=1.7",
    "platformdirs>=3.0",
    "tqdm>4.67",
]

[tool.setuptools.package-data]
delineator = [
    "data/*.db",
    "data/raster/*.tif",
    "data/vector/*.db",
]

[project.scripts]
delineate = "delineator.cli:main"
delineator_dir = "delineator.cli:delineator_dir"
delineator_download = "delineator.cli:delineator_download"

[project.urls]
Homepage = "https://github.com/mheberger/delineator"
